# https://fly.io/docs/blueprints/review-apps-guide/
[build]
  dockerfile = "Dockerfile"

[deploy]
  strategy = "immediate"

[env]
  FLATNOTES_AUTH_TYPE = 'password'
  FLATNOTES_USERNAME = 'review'
  FLATNOTES_SESSION_EXPIRY_DAYS = '1'


[[mounts]]
  source = 'data'
  destination = '/data'
  initial_size = '1gb'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[checks]
  [checks.ready]
    port = 8080
    type = 'http'
    interval = '5s'
    timeout = '2s'
    grace_period = '2s'
    method = 'GET'
    path = '/health'

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
