# https://fly.io/docs/blueprints/review-apps-guide/
name: Deploy Review App
on:
  pull_request:
    types: [opened, reopened, synchronize, closed]

jobs:
  review_app:
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      FLY_REGION: ams
      FLY_ORG: personal
    runs-on: ubuntu-latest
    outputs:
      url: ${{ steps.deploy.outputs.url }}
    concurrency:
      group: pr-${{ github.event.number }}
    environment:
      name: preview
      url: ${{ steps.deploy.outputs.url }}
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Deploy PR app to Fly.io
        id: deploy
        uses: superfly/fly-pr-review-apps@1.2.0
        with:
          name: wunschliste-pr-${{ github.event.number }}
          config: fly.review.toml
          secrets: FLATNOTES_PASSWORD={{ secrets.FLATNOTES_PASSWORD }} FLATNOTES_SECRET_KEY={{ secrets.FLATNOTES_SECRET_KEY }}
